import type { Metadata } from 'next'
import '@style/global/index.scss'

export const metadata: Metadata = {
  title: 'I see you!',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body>{children}</body>
    </html>
  )
}
